//
// Created by jeremiah on 6/17/22.
//


//NOTE: Not testing the function handleFunctionOperationException(). This is because it is just designed as a try
// catch block wrapping some exceptions. The functions that are called on these exceptions are tested elsewhere.
